global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'postgres_exporter'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ['192.168.99.100:9187']
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.99.100:8082']